## YAML Template.
---
services:
    innova.server.manager:
        class: Innova\Heartbeat\AppBundle\Manager\ServerManager
        arguments:
            entityManager: @doctrine.orm.entity_manager
    innova.serverdata.manager:
        class: Innova\Heartbeat\AppBundle\Manager\ServerDataManager
        arguments:
            documentManager: @doctrine_mongodb.odm.document_manager
            entityManager: @doctrine.orm.entity_manager

    innova.github.twig_extension:
        class: Innova\Heartbeat\AppBundle\Twig\GithubExtension
        public: false
        tags:
            - { name: twig.extension }

    innova.github.manager:
        class: Innova\Heartbeat\AppBundle\Manager\GithubManager

